import http from 'node:http';
import youtubedl from 'youtube-dl-exec';
const PORT=Number(process.env.PORT||10000), MUX='https://ivy-ytmux-backend.onrender.com';
const DEFAULT_ID='AjSxpi8E9WE', CHANNEL_HANDLE='KhoaiLangThang', ADDON_ID='community.ivy.youtube.khoailangthang', CATALOG_ID='ivy-khoai-lang-thang';
const HQ=[2160,1440,1080,720,480], videoMap=new Map(), discoveryJobs=new Map();let catalogLoading=false,catalogLoadedAt=0;
videoMap.set(DEFAULT_ID,{id:DEFAULT_ID,title:'Hành trình xuyên đảo núi lửa Iceland P5 - Du lịch Châu Âu'});
function send(res,code,body){res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'});res.end(JSON.stringify(body))}
function meta(v){return{id:`yt:${v.id}`,type:'movie',name:v.title||`YouTube ${v.id}`,poster:`https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`,background:`https://i.ytimg.com/vi/${v.id}/maxresdefault.jpg`,description:v.description||'Khoai Lang Thang / Food & Travel',genres:['YouTube','Khoai Lang Thang','Travel'],releaseInfo:'YouTube'}}
async function scan(tab){try{const d=await youtubedl(`https://www.youtube.com/@${CHANNEL_HANDLE}/${tab}`,{dumpSingleJson:true,flatPlaylist:true,skipDownload:true,noWarnings:true,ignoreErrors:true});for(const e of Array.isArray(d?.entries)?d.entries:[])if(e?.id&&/^[A-Za-z0-9_-]{11}$/.test(e.id))videoMap.set(e.id,{id:e.id,title:e.title||`YouTube ${e.id}`,description:e.description})}catch(e){console.log('[CHANNEL-SCAN-FAIL]',tab,String(e))}}
async function refreshCatalog(){if(catalogLoading||Date.now()-catalogLoadedAt<21600000)return;catalogLoading=true;try{await scan('videos');await scan('shorts');catalogLoadedAt=Date.now();console.log('[CHANNEL-CATALOG-READY]',videoMap.size)}finally{catalogLoading=false}}
async function verify(id,q){try{const r=await fetch(`${MUX}/verify/${id}/${q}.json`,{signal:AbortSignal.timeout(5000)});if(!r.ok)return null;const j=await r.json();return j.ok&&j.exactHeight&&Number(j.height)===q?j:null}catch{return null}}
async function verifiedHQ(id){for(const q of HQ){const v=await verify(id,q);if(v)return{q,v}}return null}
async function buildAndVerify(id,q){console.log('[DISCOVERY-TRY]',id,q);try{const r=await fetch(`${MUX}/stream/${id}/${q}.mp4`,{headers:{Range:'bytes=0-0'},signal:AbortSignal.timeout(180000)});if(!r.ok&&r.status!==206){console.log('[DISCOVERY-NO]',id,q,'HTTP',r.status);return null}try{await r.body?.cancel()}catch{}const v=await verify(id,q);if(v){console.log('[DISCOVERY-VERIFIED]',id,q,`${v.width}x${v.height}`,v.codec);return{q,v}}console.log('[DISCOVERY-REJECT]',id,q);return null}catch(e){console.log('[DISCOVERY-FAIL]',id,q,String(e));return null}}
function discover(id){if(discoveryJobs.has(id))return discoveryJobs.get(id);const job=(async()=>{const existing=await verifiedHQ(id);if(existing)return existing;console.log('[AUTO-DISCOVERY-SEQUENTIAL]',id);for(const q of HQ){const hit=await buildAndVerify(id,q);if(hit)return hit}return null})().finally(()=>discoveryJobs.delete(id));discoveryJobs.set(id,job);return job}
const manifest={id:ADDON_ID,version:'10.0.2',name:'Ivy ❤️ Khoai Lang Thang',description:'Full channel. Native HQ discovery runs sequentially high-to-low and AUTO appears only after ffprobe verifies the actual file.',resources:['catalog','meta','stream'],types:['movie'],catalogs:[{type:'movie',id:CATALOG_ID,name:'Khoai Lang Thang • Full Channel'}],idPrefixes:['yt:']};
http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*'});return res.end()}const path=decodeURIComponent(new URL(req.url,'http://x').pathname);if(path==='/')return send(res,200,{service:manifest.name,version:manifest.version,videos:videoMap.size,discovery:'sequential-high-to-low'});if(path==='/manifest.json')return send(res,200,manifest);if(path===`/catalog/movie/${CATALOG_ID}.json`){void refreshCatalog();return send(res,200,{metas:[...videoMap.values()].map(meta)})}let m=path.match(/^\/meta\/movie\/yt:([A-Za-z0-9_-]{11})\.json$/);if(m)return send(res,200,{meta:meta(videoMap.get(m[1])||{id:m[1]})});m=path.match(/^\/stream\/movie\/yt:([A-Za-z0-9_-]{11})\.json$/);if(m){const id=m[1];let h=await verifiedHQ(id);if(!h)void discover(id);const streams=[];if(h){streams.push({name:`AUTO • VERIFIED ${h.q}p`,title:`AUTO • actual ${h.v.width}x${h.v.height} ${h.v.codec||''}`,url:`${MUX}/stream/${id}/${h.q}.mp4`,behaviorHints:{notWebReady:true}});for(const q of HQ){const v=q===h.q?h.v:await verify(id,q);if(v)streams.push({name:`Ivy YouTube • ${q}p • VERIFIED`,title:`actual ${v.width}x${v.height} ${v.codec||''}`,url:`${MUX}/stream/${id}/${q}.mp4`,behaviorHints:{notWebReady:true}})}}streams.push({name:'Ivy YouTube • 360p',title:h?'360p direct':'HQ discovery is running sequentially • refresh streams shortly',url:`${MUX}/stream/${id}/360.mp4`,behaviorHints:{notWebReady:true}});console.log('[STREAMS]',id,h?`AUTO=${h.q}`:'AUTO=PENDING');return send(res,200,{streams})}return send(res,404,{error:'not found'})}catch(e){console.log('[ERROR]',String(e));return send(res,502,{error:String(e)})}}).listen(PORT,'0.0.0.0',()=>{console.log('[START Ivy full channel v10.0.2]',PORT);void refreshCatalog()});