import http from 'node:http';
import youtubedl from 'youtube-dl-exec';
const PORT=Number(process.env.PORT||10000), MUX='https://ivy-ytmux-backend.onrender.com';
const DEFAULT_ID='AjSxpi8E9WE', CHANNEL_HANDLE='KhoaiLangThang', ADDON_ID='community.ivy.youtube.khoailangthang', CATALOG_ID='ivy-khoai-lang-thang';
const videoMap=new Map(),nativeCache=new Map();let catalogLoading=false,catalogLoadedAt=0;
videoMap.set(DEFAULT_ID,{id:DEFAULT_ID,title:'Hành trình xuyên đảo núi lửa Iceland P5 - Du lịch Châu Âu'});
function send(res,code,body){res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'});res.end(JSON.stringify(body))}
function meta(v){return{id:`yt:${v.id}`,type:'movie',name:v.title||`YouTube ${v.id}`,poster:`https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`,background:`https://i.ytimg.com/vi/${v.id}/maxresdefault.jpg`,description:v.description||'Khoai Lang Thang / Food & Travel',genres:['YouTube','Khoai Lang Thang','Travel'],releaseInfo:'YouTube'}}
async function scan(tab){try{const d=await youtubedl(`https://www.youtube.com/@${CHANNEL_HANDLE}/${tab}`,{dumpSingleJson:true,flatPlaylist:true,skipDownload:true,noWarnings:true,ignoreErrors:true});for(const e of Array.isArray(d?.entries)?d.entries:[])if(e?.id&&/^[A-Za-z0-9_-]{11}$/.test(e.id))videoMap.set(e.id,{id:e.id,title:e.title||`YouTube ${e.id}`,description:e.description})}catch(e){console.log('[CHANNEL-SCAN-FAIL]',tab,String(e))}}
async function refreshCatalog(){if(catalogLoading||Date.now()-catalogLoadedAt<21600000)return;catalogLoading=true;try{await scan('videos');await scan('shorts');catalogLoadedAt=Date.now();console.log('[CHANNEL-CATALOG-READY]',videoMap.size)}finally{catalogLoading=false}}
async function native(id){const c=nativeCache.get(id);if(c&&c.exp>Date.now())return c.v;try{const r=await fetch(`${MUX}/native/${id}.json`,{signal:AbortSignal.timeout(45000)});if(!r.ok)return null;const j=await r.json();if(!j.verified||![2160,1440,1080,720,480].includes(Number(j.quality)))return null;const v={q:Number(j.quality),width:Number(j.width),height:Number(j.height),codec:j.codec||''};nativeCache.set(id,{v,exp:Date.now()+21600000});console.log('[AUTO-NATIVE]',id,v.q,`${v.width}x${v.height}`,v.codec);return v}catch(e){console.log('[AUTO-NATIVE-FAIL]',id,String(e));return null}}
const manifest={id:ADDON_ID,version:'10.1.0',name:'Ivy ❤️ Khoai Lang Thang',description:'Full channel. AUTO resolution comes from fast ffprobe inspection before playback; no full-file cache is required to discover HQ.',resources:['catalog','meta','stream'],types:['movie'],catalogs:[{type:'movie',id:CATALOG_ID,name:'Khoai Lang Thang • Full Channel'}],idPrefixes:['yt:']};
http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*'});return res.end()}const path=decodeURIComponent(new URL(req.url,'http://x').pathname);if(path==='/')return send(res,200,{service:manifest.name,version:manifest.version,videos:videoMap.size,nativeAuto:true});if(path==='/manifest.json')return send(res,200,manifest);if(path===`/catalog/movie/${CATALOG_ID}.json`){void refreshCatalog();return send(res,200,{metas:[...videoMap.values()].map(meta)})}let m=path.match(/^\/meta\/movie\/yt:([A-Za-z0-9_-]{11})\.json$/);if(m)return send(res,200,{meta:meta(videoMap.get(m[1])||{id:m[1]})});m=path.match(/^\/stream\/movie\/yt:([A-Za-z0-9_-]{11})\.json$/);if(m){const id=m[1],n=await native(id),streams=[];if(n)streams.push({name:`AUTO • ${n.q}p`,title:`ffprobe ${n.width}x${n.height} ${n.codec}`,url:`${MUX}/stream/${id}/${n.q}.mp4`,behaviorHints:{notWebReady:true}});streams.push({name:'Ivy YouTube • 360p',title:n?'360p fallback':'Native HQ probe unavailable • 360p fallback',url:`${MUX}/stream/${id}/360.mp4`,behaviorHints:{notWebReady:true}});console.log('[STREAMS]',id,n?`AUTO=${n.q}`:'AUTO=NONE');return send(res,200,{streams})}return send(res,404,{error:'not found'})}catch(e){console.log('[ERROR]',String(e));return send(res,502,{error:String(e)})}}).listen(PORT,'0.0.0.0',()=>{console.log('[START Ivy full channel v10.1.0]',PORT);void refreshCatalog()});