import http from 'node:http';
import {spawn} from 'node:child_process';
import {Readable} from 'node:stream';
import ffmpegPath from 'ffmpeg-static';

const PORT=Number(process.env.PORT||10000);
const PROVIDER='https://youtubeone.vercel.app';
const UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 Version/18.5 Mobile/15E148 Safari/604.1';
const Q=[2160,1440,1080,720,480,360];
const cache=new Map(),inFlight=new Map(),playableCache=new Map();
function send(res,code,obj){res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'});res.end(JSON.stringify(obj));}
async function getInfo(id){const h=cache.get(id);if(h&&h.expires>Date.now())return h.info;if(inFlight.has(id))return inFlight.get(id);const p=(async()=>{const r=await fetch(`${PROVIDER}/api/info`,{method:'POST',headers:{'content-type':'application/json','user-agent':UA},body:JSON.stringify({url:`https://www.youtube.com/watch?v=${id}`}),signal:AbortSignal.timeout(30000)}),j=await r.json().catch(()=>null);if(!r.ok||!Array.isArray(j?.formats))throw new Error(`provider info ${r.status}`);cache.set(id,{info:j,expires:Date.now()+600000});console.log('[YO-INFO]',id,'node',j.node,'formats',j.formats.length);return j;})().finally(()=>inFlight.delete(id));inFlight.set(id,p);return p;}
function streamProxy(info,f,name){const u=new URL(`${PROVIDER}/api/stream`);u.searchParams.set('url',f.url);u.searchParams.set('filename',name);if(info.proxied){u.searchParams.set('proxied','1');u.searchParams.set('node',String(info.node));}return u.toString();}
function codecRank(f,q){const m=String(f.mimeType||'').toLowerCase();let r=0;if(m.includes('avc1'))r+=q<=1080?120:20;if(m.includes('vp9')||m.includes('vp09'))r+=q>1080?100:50;if(m.includes('av01'))r+=q>1080?90:10;if(m.startsWith('video/mp4'))r+=30;return r+(f.bitrate||0)/1e8;}
function pickExact(info,q){const fs=info.formats||[];const muxed=fs.filter(f=>f.type==='muxed'&&f.url&&Number(f.height)===q).sort((a,b)=>(b.bitrate||0)-(a.bitrate||0))[0];if(muxed)return{kind:'direct',format:muxed};const video=fs.filter(f=>f.type==='video'&&f.url&&Number(f.height)===q).sort((a,b)=>codecRank(b,q)-codecRank(a,q))[0];const audio=fs.filter(f=>f.type==='audio'&&f.url).sort((a,b)=>{const A=String(a.mimeType||'').includes('mp4')?1:0,B=String(b.mimeType||'').includes('mp4')?1:0;return(B-A)||((b.bitrate||0)-(a.bitrate||0));})[0];return video&&audio?{kind:'mux',video,audio}:null;}
async function readSmall(r,limit=32768){const rd=r.body?.getReader();if(!rd)return 0;let n=0;try{while(n<limit){const x=await rd.read();if(x.done)break;n+=x.value.byteLength;}}finally{try{await rd.cancel();}catch{}}return n;}
async function probeDirect(info,f,id,q){try{const r=await fetch(streamProxy(info,f,`${id}-${q}.mp4`),{headers:{Range:'bytes=0-32767','User-Agent':UA},signal:AbortSignal.timeout(12000)}),bytes=await readSmall(r),ok=(r.status===200||r.status===206)&&bytes>0;console.log('[DIRECT-PROBE]',id,q,r.status,bytes,ok);return ok;}catch(e){console.log('[DIRECT-PROBE-FAIL]',id,q,String(e));return false;}}
async function fetchInput(url){const r=await fetch(url,{headers:{'User-Agent':UA,Accept:'*/*'},redirect:'follow',signal:AbortSignal.timeout(20000)});if(!r.ok||!r.body)throw new Error(`input ${r.status}`);return Readable.fromWeb(r.body);}
async function startMux(info,p,id,q,{probe=false,res=null}={}){const vurl=streamProxy(info,p.video,`${id}-${q}-video`),aurl=streamProxy(info,p.audio,`${id}-${q}-audio`);const [vs,as]=await Promise.all([fetchInput(vurl),fetchInput(aurl)]);const args=['-nostdin','-hide_banner','-loglevel','warning','-i','pipe:3','-i','pipe:4','-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','copy','-movflags','frag_keyframe+empty_moov+default_base_moof','-f','mp4','pipe:1'];const ff=spawn(ffmpegPath,args,{stdio:['ignore','pipe','pipe','pipe','pipe']});let bytes=0,done=false,streamFailed=false;
const safeErr=(where)=>(e)=>{streamFailed=true;console.log('[PIPE-ERROR]',id,q,where,e?.code||'',String(e?.message||e));};
vs.on('error',safeErr('video-input'));as.on('error',safeErr('audio-input'));ff.stdio[3].on('error',safeErr('ff-video-pipe'));ff.stdio[4].on('error',safeErr('ff-audio-pipe'));ff.stdout.on('error',safeErr('ff-stdout'));ff.stderr.on('error',safeErr('ff-stderr'));
vs.pipe(ff.stdio[3]);as.pipe(ff.stdio[4]);ff.stderr.on('data',d=>console.log('[FFMPEG]',id,q,String(d).trim()));return await new Promise(resolve=>{const cleanup=()=>{try{vs.unpipe(ff.stdio[3]);as.unpipe(ff.stdio[4]);}catch{}try{vs.destroy();as.destroy();}catch{}};const finish=(ok)=>{if(done)return;done=true;clearTimeout(timer);cleanup();if(probe&&!ff.killed)ff.kill('SIGKILL');resolve(Boolean(ok)&&!streamFailed);};const timer=setTimeout(()=>{console.log('[MUX-PROBE-TIMEOUT]',id,q,bytes);if(!ff.killed)ff.kill('SIGKILL');finish(false);},probe?15000:90000);ff.stdout.on('data',c=>{bytes+=c.length;if(bytes===c.length)console.log('[MUX-FIRST-BYTES]',id,q,c.length);if(res&&!res.writableEnded)res.write(c);if(probe&&bytes>=32768)finish(true);});ff.on('error',e=>{console.log('[MUX-SPAWN-ERR]',id,q,String(e));finish(false);});ff.on('close',(code,signal)=>{console.log('[MUX-CLOSE]',id,q,'code',code,'signal',signal,'bytes',bytes,'streamFailed',streamFailed);if(res&&!res.writableEnded)res.end();finish(bytes>0&&!streamFailed);});});}
async function playable(id){const h=playableCache.get(id);if(h&&h.expires>Date.now())return h.q;const info=await getInfo(id),out=[];for(const q of Q){const p=pickExact(info,q);if(!p)continue;let ok=false;if(p.kind==='direct')ok=await probeDirect(info,p.format,id,q);else try{ok=await startMux(info,p,id,q,{probe:true});}catch(e){console.log('[MUX-PROBE-FAIL]',id,q,String(e));}if(ok)out.push(q);}playableCache.set(id,{q:out,expires:Date.now()+(out.length?600000:30000)});console.log('[PLAYABLE]',id,out.join(','));return out;}
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;if(path==='/')return send(res,200,{service:'Ivy residential mux backend',version:'0.5.1'});let m=path.match(/^\/availability\/([A-Za-z0-9_-]{11})\.json$/);if(m){const info=await getInfo(m[1]);const heights=[...new Set(info.formats.filter(f=>f.url&&f.height&&['video','muxed'].includes(f.type)).map(f=>Number(f.height)))].filter(x=>Q.includes(x)).sort((a,b)=>b-a);return send(res,200,{ok:true,id:m[1],supported:heights});}m=path.match(/^\/playable\/([A-Za-z0-9_-]{11})\.json$/);if(m)return send(res,200,{ok:true,id:m[1],playableDirect:await playable(m[1])});m=path.match(/^\/stream\/([A-Za-z0-9_-]{11})\/(2160|1440|1080|720|480|360)\.mp4$/);if(m){const [,id,qs]=m,q=Number(qs),info=await getInfo(id),p=pickExact(info,q);if(!p)return send(res,404,{error:'quality unavailable',id,q});if(p.kind==='direct'){const u=streamProxy(info,p.format,`${id}-${q}.mp4`);res.writeHead(302,{Location:u,'Cache-Control':'no-store','Access-Control-Allow-Origin':'*','X-Ivy-Height':String(q),'X-Ivy-Mode':'direct'});return res.end();}res.writeHead(200,{'Content-Type':'video/mp4','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Transfer-Encoding':'chunked','X-Ivy-Height':String(q),'X-Ivy-Mode':'node-pipe-mux'});console.log('[MUX-START]',id,q,p.video.mimeType,p.audio.mimeType);await startMux(info,p,id,q,{res});return;}return send(res,404,{error:'not found',path});}catch(e){console.error('[ERROR]',String(e));if(!res.headersSent)return send(res,502,{error:String(e)});if(!res.writableEnded)res.end();}});
process.on('uncaughtException',e=>console.error('[UNCAUGHT]',e?.code||'',String(e)));
process.on('unhandledRejection',e=>console.error('[UNHANDLED]',String(e)));
server.listen(PORT,'0.0.0.0',()=>console.log('Ivy residential mux backend listening',PORT));