import http from 'node:http';
import {spawn} from 'node:child_process';
import {Readable} from 'node:stream';
import {createReadStream,createWriteStream,existsSync,statSync,mkdirSync,renameSync,unlinkSync} from 'node:fs';
import {join} from 'node:path';
import ffmpegPath from 'ffmpeg-static';
const PORT=Number(process.env.PORT||10000), PROVIDER='https://youtubeone.vercel.app', DIR='/tmp/ivy-media';
const UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 Version/18.5 Mobile/15E148 Safari/604.1';
mkdirSync(DIR,{recursive:true});const cache=new Map(),jobs=new Map();
function send(res,c,o){res.writeHead(c,{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':'*'});res.end(JSON.stringify(o))}
async function getInfo(id){const h=cache.get(id);if(h&&h.exp>Date.now())return h.j;const r=await fetch(`${PROVIDER}/api/info`,{method:'POST',headers:{'content-type':'application/json','user-agent':UA},body:JSON.stringify({url:`https://www.youtube.com/watch?v=${id}`}),signal:AbortSignal.timeout(30000)}),j=await r.json();if(!r.ok||!Array.isArray(j.formats))throw new Error(`provider info ${r.status}`);cache.set(id,{j,exp:Date.now()+600000});return j}
function proxy(info,f,name){const u=new URL(`${PROVIDER}/api/stream`);u.searchParams.set('url',f.url);u.searchParams.set('filename',name);if(info.proxied){u.searchParams.set('proxied','1');u.searchParams.set('node',String(info.node))}return u.toString()}
function pick(info,q){const fs=info.formats||[];const mux=fs.filter(f=>f.type==='muxed'&&f.url&&Number(f.height)===q).sort((a,b)=>(b.bitrate||0)-(a.bitrate||0))[0];if(mux)return{kind:'direct',format:mux};const video=fs.filter(f=>f.type==='video'&&f.url&&Number(f.height)===q&&String(f.mimeType||'').includes('mp4')).sort((a,b)=>(b.bitrate||0)-(a.bitrate||0))[0];const audio=fs.filter(f=>f.type==='audio'&&f.url&&String(f.mimeType||'').includes('mp4')).sort((a,b)=>(b.bitrate||0)-(a.bitrate||0))[0];return video&&audio?{kind:'mux',video,audio}:null}
async function input(url){const r=await fetch(url,{headers:{'user-agent':UA},redirect:'follow'});if(!r.ok||!r.body)throw new Error(`input ${r.status}`);return Readable.fromWeb(r.body)}
function file(id,q){return join(DIR,`${id}-${q}.mp4`)}
async function build(id,q){const key=`${id}:${q}`;if(jobs.has(key))return jobs.get(key);const job=(async()=>{const info=await getInfo(id),p=pick(info,q);if(!p)throw new Error('quality unavailable');const out=file(id,q),tmp=out+'.part';try{unlinkSync(tmp)}catch{}if(p.kind==='direct'){const r=await fetch(proxy(info,p.format,`${id}-${q}.mp4`),{redirect:'follow'});if(!r.ok||!r.body)throw new Error(`direct ${r.status}`);await new Promise((ok,no)=>{const w=createWriteStream(tmp);Readable.fromWeb(r.body).on('error',no).pipe(w).on('finish',ok).on('error',no)})}else{const [v,a]=await Promise.all([input(proxy(info,p.video,`${id}-${q}-v`)),input(proxy(info,p.audio,`${id}-${q}-a`))]);await new Promise((ok,no)=>{const ff=spawn(ffmpegPath,['-nostdin','-hide_banner','-loglevel','error','-i','pipe:3','-i','pipe:4','-map','0:v:0','-map','1:a:0','-c','copy','-movflags','+faststart','-f','mp4',tmp],{stdio:['ignore','ignore','pipe','pipe','pipe']});v.on('error',no);a.on('error',no);ff.stdio[3].on('error',()=>{});ff.stdio[4].on('error',()=>{});v.pipe(ff.stdio[3]);a.pipe(ff.stdio[4]);ff.stderr.on('data',d=>console.log('[FF]',id,q,String(d).trim()));ff.on('error',no);ff.on('close',c=>c===0?ok():no(new Error(`ffmpeg ${c}`)))})}renameSync(tmp,out);console.log('[READY-SEEKABLE]',id,q,statSync(out).size);return out})().finally(()=>jobs.delete(key));jobs.set(key,job);return job}
function serve(req,res,p){const size=statSync(p).size,range=req.headers.range;const common={'content-type':'video/mp4','accept-ranges':'bytes','cache-control':'public, max-age=3600','access-control-allow-origin':'*'};if(!range){res.writeHead(200,{...common,'content-length':size});return createReadStream(p).pipe(res)}const m=/bytes=(\d*)-(\d*)/.exec(range);if(!m){res.writeHead(416,{'content-range':`bytes */${size}`});return res.end()}let start=m[1]?Number(m[1]):0,end=m[2]?Number(m[2]):size-1;if(!m[1]&&m[2]){start=Math.max(0,size-Number(m[2]));end=size-1}end=Math.min(end,size-1);if(start>end||start>=size){res.writeHead(416,{'content-range':`bytes */${size}`});return res.end()}res.writeHead(206,{...common,'content-length':end-start+1,'content-range':`bytes ${start}-${end}/${size}`});createReadStream(p,{start,end}).pipe(res)}
process.on('uncaughtException',e=>console.log('[UNCAUGHT]',String(e)));process.on('unhandledRejection',e=>console.log('[REJECTION]',String(e)));
http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://x').pathname;if(path==='/')return send(res,200,{ok:true,version:'0.7.0',playback:'seekable-faststart-mp4',range:true});const m=path.match(/^\/stream\/([A-Za-z0-9_-]{11})\/(2160|1440|1080|720|480|360)\.mp4$/);if(!m)return send(res,404,{error:'not found'});const [,id,s]=m,q=Number(s),p=file(id,q);if(!existsSync(p)){console.log('[BUILD]',id,q);await build(id,q)}return serve(req,res,p)}catch(e){console.log('[ERROR]',String(e));if(!res.headersSent)send(res,502,{error:String(e)});else if(!res.writableEnded)res.end()}}).listen(PORT,'0.0.0.0',()=>console.log('backend 0.7.0',PORT));