import http from 'node:http';
import {spawn} from 'node:child_process';
import {Readable} from 'node:stream';
import ffmpegPath from 'ffmpeg-static';
import ffprobeStatic from 'ffprobe-static';

const PORT=Number(process.env.PORT||10000);
const PROVIDER='https://youtubeone.vercel.app';
const UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 Version/18.5 Mobile/15E148 Safari/604.1';
const Q=[2160,1440,1080,720,480,360];
const cache=new Map(),inFlight=new Map(),verifiedCache=new Map();
function send(res,code,obj){res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'});res.end(JSON.stringify(obj));}
async function getInfo(id){const h=cache.get(id);if(h&&h.expires>Date.now())return h.info;if(inFlight.has(id))return inFlight.get(id);const p=(async()=>{const r=await fetch(`${PROVIDER}/api/info`,{method:'POST',headers:{'content-type':'application/json','user-agent':UA},body:JSON.stringify({url:`https://www.youtube.com/watch?v=${id}`}),signal:AbortSignal.timeout(30000)}),j=await r.json().catch(()=>null);if(!r.ok||!Array.isArray(j?.formats))throw new Error(`provider info ${r.status}`);cache.set(id,{info:j,expires:Date.now()+600000});console.log('[YO-INFO]',id,'node',j.node,'formats',j.formats.length);return j;})().finally(()=>inFlight.delete(id));inFlight.set(id,p);return p;}
function streamProxy(info,f,name){const u=new URL(`${PROVIDER}/api/stream`);u.searchParams.set('url',f.url);u.searchParams.set('filename',name);if(info.proxied){u.searchParams.set('proxied','1');u.searchParams.set('node',String(info.node));}return u.toString();}
function codecRank(f,q){const m=String(f.mimeType||'').toLowerCase();let r=0;if(m.includes('avc1'))r+=q<=1080?120:20;if(m.includes('vp9')||m.includes('vp09'))r+=q>1080?100:50;if(m.includes('av01'))r+=q>1080?90:10;if(m.startsWith('video/mp4'))r+=30;return r+(f.bitrate||0)/1e8;}
function pickExact(info,q){const fs=info.formats||[];const muxed=fs.filter(f=>f.type==='muxed'&&f.url&&Number(f.height)===q).sort((a,b)=>(b.bitrate||0)-(a.bitrate||0))[0];if(muxed)return{kind:'direct',format:muxed};const video=fs.filter(f=>f.type==='video'&&f.url&&Number(f.height)===q).sort((a,b)=>codecRank(b,q)-codecRank(a,q))[0];const audio=fs.filter(f=>f.type==='audio'&&f.url).sort((a,b)=>{const A=String(a.mimeType||'').includes('mp4')?1:0,B=String(b.mimeType||'').includes('mp4')?1:0;return(B-A)||((b.bitrate||0)-(a.bitrate||0));})[0];return video&&audio?{kind:'mux',video,audio}:null;}
async function probeDimensions(url,id,claimed){return await new Promise(resolve=>{const args=['-v','error','-select_streams','v:0','-show_entries','stream=width,height,codec_name,r_frame_rate:format=duration','-of','json',url];const p=spawn(ffprobeStatic.path,args,{stdio:['ignore','pipe','pipe']});let out='',err='',done=false;const finish=v=>{if(done)return;done=true;clearTimeout(timer);resolve(v)};const timer=setTimeout(()=>{p.kill('SIGKILL');console.log('[FFPROBE-TIMEOUT]',id,claimed);finish(null)},25000);p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',e=>{console.log('[FFPROBE-ERROR]',id,claimed,String(e));finish(null)});p.on('close',()=>{if(done)return;try{const j=JSON.parse(out),s=j.streams?.[0];if(!s?.width||!s?.height){console.log('[FFPROBE-NODIM]',id,claimed,err.slice(0,180));return finish(null)}const actual={width:Number(s.width),height:Number(s.height),codec:s.codec_name||'',fps:s.r_frame_rate||'',duration:Number(j.format?.duration)||null};console.log('[ACTUAL-RESOLUTION]',id,'claimed',claimed,'actual',`${actual.width}x${actual.height}`,'codec',actual.codec,'duration',actual.duration);finish(actual)}catch{console.log('[FFPROBE-PARSE-FAIL]',id,claimed,err.slice(0,180));finish(null)}})})}
async function verifyOne(info,id,q){const p=pickExact(info,q);if(!p)return null;const f=p.kind==='direct'?p.format:p.video;console.log('[SOURCE-FORMAT]',id,'claimed',q,'itag',f.itag||f.formatId||'',f.mimeType||'',f.width||'',f.height||'',f.fps||'');const actual=await probeDimensions(streamProxy(info,f,`${id}-${q}-verify`),id,q);if(!actual)return null;const ok=actual.height===q;console.log('[VERIFY-QUALITY]',id,'requested',q,'actual',`${actual.width}x${actual.height}`,'verified',ok);return ok?{q,...actual}:null;}
async function verified(id){const h=verifiedCache.get(id);if(h&&h.expires>Date.now())return h.items;const info=await getInfo(id);const candidates=[...new Set(info.formats.filter(f=>f.url&&f.height&&['video','muxed'].includes(f.type)).map(f=>Number(f.height)))].filter(q=>Q.includes(q)).sort((a,b)=>b-a);const items=(await Promise.all(candidates.map(q=>verifyOne(info,id,q)))).filter(Boolean).sort((a,b)=>b.q-a.q);verifiedCache.set(id,{items,expires:Date.now()+600000});console.log('[VERIFIED-RESOLUTIONS]',id,items.map(x=>`${x.q}:${x.width}x${x.height}`).join(','));return items;}
async function fetchInput(url){const r=await fetch(url,{headers:{'User-Agent':UA,Accept:'*/*'},redirect:'follow'});if(!r.ok||!r.body)throw new Error(`input ${r.status}`);return Readable.fromWeb(r.body);}
async function startMux(info,p,id,q,res){const [vs,as]=await Promise.all([fetchInput(streamProxy(info,p.video,`${id}-${q}-video`)),fetchInput(streamProxy(info,p.audio,`${id}-${q}-audio`))]);const args=['-nostdin','-hide_banner','-loglevel','warning','-i','pipe:3','-i','pipe:4','-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','copy','-movflags','frag_keyframe+empty_moov+default_base_moof','-f','mp4','pipe:1'];const ff=spawn(ffmpegPath,args,{stdio:['ignore','pipe','pipe','pipe','pipe']});vs.pipe(ff.stdio[3]);as.pipe(ff.stdio[4]);ff.stdout.pipe(res);ff.stderr.on('data',d=>console.log('[FFMPEG]',id,q,String(d).trim()));const stop=()=>{try{vs.destroy();as.destroy()}catch{}if(!ff.killed)ff.kill('SIGKILL')};res.on('close',stop);ff.on('close',()=>{if(!res.writableEnded)res.end()});}
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;if(path==='/')return send(res,200,{service:'Ivy residential mux backend',version:'0.6.1',qualityTruth:'real-ffprobe'});let m=path.match(/^\/availability\/([A-Za-z0-9_-]{11})\.json$/);if(m){const items=await verified(m[1]);return send(res,200,{ok:true,id:m[1],supported:items.map(x=>x.q),verified:items});}m=path.match(/^\/stream\/([A-Za-z0-9_-]{11})\/(2160|1440|1080|720|480|360)\.mp4$/);if(m){const [,id,qs]=m,q=Number(qs);if(q!==360){const items=await verified(id);if(!items.some(x=>x.q===q))return send(res,404,{error:'requested quality failed actual-resolution verification',id,q});}const info=await getInfo(id),p=pickExact(info,q);if(!p)return send(res,404,{error:'quality unavailable',id,q});console.log('[PLAY]',id,'requested',q,p.kind);if(p.kind==='direct'){res.writeHead(302,{Location:streamProxy(info,p.format,`${id}-${q}.mp4`),'Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});return res.end();}res.writeHead(200,{'Content-Type':'video/mp4','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Transfer-Encoding':'chunked'});await startMux(info,p,id,q,res);return;}return send(res,404,{error:'not found',path});}catch(e){console.error('[ERROR]',String(e));if(!res.headersSent)return send(res,502,{error:String(e)});if(!res.writableEnded)res.end();}});
server.listen(PORT,'0.0.0.0',()=>console.log('Ivy residential mux backend v0.6.1 listening',PORT));