import http from 'node:http';
const PORT=Number(process.env.PORT||10000), TEST='XwY9ysGXkI4', API='https://youtubeone.vercel.app/api/info', STREAM='https://youtubeone.vercel.app/api/stream';
const ORIGIN='https://ivy-tubio-residential-test.onrender.com';
async function info(id){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:`https://www.youtube.com/watch?v=${id}`}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`info HTTP ${r.status}`);return r.json()}
const fs=j=>j.formats||j.data?.formats||[];
function muxed360(j){return fs(j).filter(f=>+f.height<=360&&f.url&&f.vcodec&&f.vcodec!=='none'&&f.acodec&&f.acodec!=='none').sort((a,b)=>(b.height||0)-(a.height||0)||(b.tbr||0)-(a.tbr||0))[0]}
function proxied(j,f,id){if(!(j.proxied&&j.node!=null))return f.url;const u=new URL(STREAM);u.searchParams.set('url',f.url);u.searchParams.set('filename',`${id}-360.mp4`);u.searchParams.set('proxied','true');u.searchParams.set('node',String(j.node));return u.toString()}
const manifest={id:'community.ivy.nuvio.residential.test',version:'1.0.0',name:'Ivy ❤️ Nuvio Playback Test',description:'Minimal internal-player playback test',resources:['catalog','meta','stream'],types:['movie'],catalogs:[{type:'movie',id:'ivytest',name:'Ivy ❤️ Nuvio Test'}]};
const meta={id:`yt:${TEST}`,type:'movie',name:'Nuvio Playback Test - Khoai Lang Thang',poster:`https://i.ytimg.com/vi/${TEST}/hqdefault.jpg`,description:'360p muxed video+audio residential playback test'};
function json(res,obj,status=200){res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*'});res.end(JSON.stringify(obj))}
const server=http.createServer(async(req,res)=>{try{console.log('[REQ]',req.method,req.url);if(req.url==='/manifest.json')return json(res,manifest);if(req.url==='/catalog/movie/ivytest.json')return json(res,{metas:[meta]});if(req.url===`/meta/movie/yt:${TEST}.json`||req.url===`/meta/movie/yt%3A${TEST}.json`)return json(res,{meta});if(req.url===`/stream/movie/yt:${TEST}.json`||req.url===`/stream/movie/yt%3A${TEST}.json`){const j=await info(TEST),f=muxed360(j);if(!f){console.log('[NUVIO-NO-MUXED]');return json(res,{streams:[]})}const target=proxied(j,f,TEST);console.log('[NUVIO-STREAM]',JSON.stringify({height:f.height,format:f.format_id||f.itag,ext:f.ext,proxied:j.proxied,node:j.node}));return json(res,{streams:[{name:'Ivy ❤️ Test',title:`${f.height||360}p • video + audio`,url:target,behaviorHints:{notWebReady:true}}]})}if(req.url==='/health')return json(res,{ok:true,manifest:`${ORIGIN}/manifest.json`});return json(res,{service:'ivy-nuvio-playback-test',manifest:`${ORIGIN}/manifest.json`})}catch(e){console.error('[ERR]',e);json(res,{error:e.message},502)}});
server.listen(PORT,'0.0.0.0',()=>console.log('[START]',PORT,`${ORIGIN}/manifest.json`));