import http from 'node:http';
const PORT=Number(process.env.PORT||10000);
const ID='XwY9ysGXkI4';
const YT=`https://www.youtube.com/watch?v=${ID}`;
const manifest={id:'community.ivy.m3u.youtube.original.test',version:'1.0.0',name:'Ivy M3U YouTube Original Test',description:'Isolated Nuvio test: original YouTube watch URL is passed through exactly as an M3U/IPTV stream. No SaveTube, SaveFrom, yt-dlp or resolver.',resources:['catalog','meta','stream'],types:['tv'],catalogs:[{type:'tv',id:'youtube-m3u-test',name:'YouTube M3U Test'}],idPrefixes:['m3uyt:']};
const meta={id:`m3uyt:${ID}`,type:'tv',name:'Khoai Test - Original YouTube URL',poster:`https://i.ytimg.com/vi/${ID}/hqdefault.jpg`,description:'Original youtube.com/watch URL passed directly to Nuvio.'};
function json(res,code,obj){res.writeHead(code,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':'no-store'});res.end(JSON.stringify(obj));}
const server=http.createServer((req,res)=>{const p=decodeURIComponent(new URL(req.url,'http://x').pathname);console.log(req.method,p);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*'});return res.end();}if(p==='/')return json(res,200,{ok:true,name:manifest.name,version:manifest.version,source:YT});if(p==='/test.m3u'){res.writeHead(200,{'content-type':'audio/x-mpegurl; charset=utf-8','access-control-allow-origin':'*','cache-control':'no-store'});return res.end(`#EXTM3U\n#EXTINF:-1 tvg-id="${ID}" tvg-name="Khoai Test - YouTube Original URL" tvg-logo="https://i.ytimg.com/vi/${ID}/hqdefault.jpg" group-title="YouTube M3U Test",Khoai Test - ${ID}\n${YT}\n`);}if(p==='/manifest.json')return json(res,200,manifest);if(p==='/catalog/tv/youtube-m3u-test.json')return json(res,200,{metas:[meta]});if(p===`/meta/tv/m3uyt:${ID}.json`)return json(res,200,{meta});if(p===`/stream/tv/m3uyt:${ID}.json`)return json(res,200,{streams:[{name:'Original YouTube URL • M3U passthrough',title:'No resolver — exact URL from M3U',url:YT}]});return json(res,404,{error:'not found'});});
server.listen(PORT,'0.0.0.0',()=>console.log('Ivy M3U YouTube original test listening',PORT));
